swipe:
  3:
    left:
      command: "xdotool key alt+Left" # History forward 
    right:
      command: "xdotool key alt+Right" # History back
    up:
      command: "xdotool key super+q" # Activity
    down:
      command: "xdotool key ctrl+w" # Activity
  4:
    left:
      command: "xdotool key super+period" # Switch to next workspace
    right:
      command: "xdotool key super+comma" # Switch to previous workspace
    up:
      command: "xdotool key super+p" # Switch to previous workspace
    down:
      command: "xdotool key super+shift+space" # Activity
pinch:
  2:
    in:
      command: "xdotool key ctrl+minus" # Zoom in
      threshold: 0.2
    out:
      command: "xdotool key ctrl+equal" # Zoom out
      threshold: 0.2

interval:
  swipe: 1
  pinch: 1
